name: flowdash-bio
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - flask=1.1.2
  - flask-login=0.5.0
  - flask-migrate=2.4.0
  - flask-wtf=0.14.3
  - flask-sqlalchemy=2.*
  - email-validator=1.1.1
  - python-decouple=3.3
  - gunicorn=20.0.4
  - python-dotenv=0.14.0
  - flask-bootstrap=3.3.7.1
  - flask-mail=0.9.1
  - psycopg2=2.8.6
  - postgresql=12.3
  - flask-jwt-extended=3.24.1
  - flask-restful=0.3.8
  - Flask-HTTPAuth=4.1.0
  - conda-forge::pyngrok=5.0.0
