"""remove test fields

Revision ID: 0356961cd446
Revises: 3c1e088f223a
Create Date: 2020-10-25 19:14:56.113642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0356961cd446'
down_revision = '3c1e088f223a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_field')
    op.drop_column('user', 'test_field2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_field2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('test_field', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
