"""test migrate for production

Revision ID: 204c97026914
Revises: e7cd98b0da4d
Create Date: 2020-10-25 19:04:31.943059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204c97026914'
down_revision = 'e7cd98b0da4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_field', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'test_field')
    # ### end Alembic commands ###
