"""add test_field2 to user

Revision ID: 3c1e088f223a
Revises: 204c97026914
Create Date: 2020-10-25 19:07:24.222534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1e088f223a'
down_revision = '204c97026914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_field2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_field2')
    # ### end Alembic commands ###
