"""add user avatar

Revision ID: 510a9bbcba5c
Revises: bd3c8fae4ac2
Create Date: 2020-10-25 13:23:14.332403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510a9bbcba5c'
down_revision = 'bd3c8fae4ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
