"""empty message

Revision ID: 864659d79b3f
Revises: acd99c0cd557
Create Date: 2020-10-25 17:09:27.224388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864659d79b3f'
down_revision = 'acd99c0cd557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_registered_on'), 'user', ['registered_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registered_on'), table_name='user')
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###
