"""add column user_id to workflow

Revision ID: 867908b5c145
Revises: 385401018742
Create Date: 2020-10-24 20:20:02.545294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867908b5c145'
down_revision = '385401018742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflow', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'user_id')
    # ### end Alembic commands ###
