"""add registered on to user

Revision ID: acd99c0cd557
Revises: 
Create Date: 2020-10-25 17:01:52.033796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd99c0cd557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_registered_on'), ['registered_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_registered_on'))
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###
