"""remove username from workflow

Revision ID: ba21cddd3c6c
Revises: fa966deaf828
Create Date: 2020-10-24 20:54:04.940752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba21cddd3c6c'
down_revision = 'fa966deaf828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_workflow_username', ['username'], unique=False)

    # ### end Alembic commands ###
