"""added is_admin to user: production

Revision ID: de674a11d4ed
Revises: 0a98d5c730b4
Create Date: 2020-10-25 17:22:53.183726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de674a11d4ed'
down_revision = '0a98d5c730b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_registered_on'), 'user', ['registered_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registered_on'), table_name='user')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
