"""add column user_id to workflow

Revision ID: fa966deaf828
Revises: b287722af204
Create Date: 2020-10-24 20:39:38.677025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa966deaf828'
down_revision = 'b287722af204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_workflow_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workflow_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
